/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const LogoutLazyImport = createFileRoute('/logout')()
const CreateTaskLazyImport = createFileRoute('/create-task')()

// Create/Update Routes

const LogoutLazyRoute = LogoutLazyImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/logout.lazy').then((d) => d.Route))

const CreateTaskLazyRoute = CreateTaskLazyImport.update({
  id: '/create-task',
  path: '/create-task',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/create-task.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-task': {
      id: '/create-task'
      path: '/create-task'
      fullPath: '/create-task'
      preLoaderRoute: typeof CreateTaskLazyImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-task': typeof CreateTaskLazyRoute
  '/logout': typeof LogoutLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-task': typeof CreateTaskLazyRoute
  '/logout': typeof LogoutLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create-task': typeof CreateTaskLazyRoute
  '/logout': typeof LogoutLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-task' | '/logout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-task' | '/logout'
  id: '__root__' | '/' | '/create-task' | '/logout'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateTaskLazyRoute: typeof CreateTaskLazyRoute
  LogoutLazyRoute: typeof LogoutLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateTaskLazyRoute: CreateTaskLazyRoute,
  LogoutLazyRoute: LogoutLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-task",
        "/logout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-task": {
      "filePath": "create-task.lazy.tsx"
    },
    "/logout": {
      "filePath": "logout.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
